### ISSUE TITLE
Error: "Not a gzipped file (b'"

### ISSUE THREAD

**Issue by tjukanovt** [GispoCoding/FMI2QGIS#56]
When I try to download WFS-layer SILAM air quality forecast as simple feature with the default parameters, I get the following error in the log messages: `CRITICAL    Unhandled exception occurred : Not a gzipped file (b'`

Query from the logs:
`Download url is is: "https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=GetFeature&storedquery_id=fmi::forecast::silam::airquality::surface::point::simple&starttime=2021-03-16T14:10:00Z&endtime=2021-03-16T14:10:00Z"`

**Comment by tjukanovt** [comment]
Full error from logs:
<details>

```

16.03.2021 10:54:42 - [INFO   ] - main_dialog.py:109 : Selected query id: fmi::observations::airquality::hourly::simple
16.03.2021 10:54:59 - [ERROR  ] - vector_loader.py:123 : Unhandled exception occurred
Traceback (most recent call last):
  File "C:/Users/Topi Tjukanov/AppData/Roaming/QGIS/QGIS3\profiles\topi/python/plugins\FMI2QGIS\core\processing\vector_loader.py", line 119, in finished
    raise self.exception
  File "C:/Users/Topi Tjukanov/AppData/Roaming/QGIS/QGIS3\profiles\topi/python/plugins\FMI2QGIS\core\processing\base_loader.py", line 80, in _download
    output = self._process_downloaded_file(output)
  File "C:/Users/Topi Tjukanov/AppData/Roaming/QGIS/QGIS3\profiles\topi/python/plugins\FMI2QGIS\core\processing\vector_loader.py", line 79, in _process_downloaded_file
    f2.write(f.read().decode('utf-8'))
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\gzip.py", line 276, in read
    return self._buffer.read(size)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<?')

```

</details>

**Comment by Joonalai** [comment]
In `VectorLoader._process_downloaded_file` it is assumed that all files are gzipped. A check should be added there.

**Comment by Joonalai** [comment]
Also occurs with id 46.
